### ISSUE TITLE
Error when closing channels, when cancelling downloads

### ISSUE THREAD

**Issue by spersico** [statechannels/monorepo#1811]
**Describe the bug :bug:**
Cancelling a download in progress fails the first time (with every torrent). Seems like cancelling triggers an invalid change of state in xstate-wallet, which makes the client throw, which blocks the torrent from being truly cancelled.https://github.com/statechannels/monorepo/blob/ad74d8d89de84288617ecfaba9f8c4b715b10b9a/packages/web3torrent/src/library/web3torrent-lib.ts#L134-L135
**Currently blocking #1781. Successfully reproduced (at least with virtual funding) in the current master, and in production.**

This results in that with both Virtual funding (with the hub) and Direct Funding, the cancel button must be pressed twice:
- With **Direct Funding**, an error log appears:
```
Browser 1 logged Missing onError handler for invocation 'signFinalState', error was 'Error: Supported state not final'. Stacktrace was 'Error: Supported state not final
    at http://localhost:3055/bundle.js:264367:15
    at Generator.next (<anonymous>)
    at fulfilled (http://localhost:3055/bundle.js:264352:58)'
```
- With **Virtual Funding**, no error got logged, though, between the logs, a couple of warnings can be seen :
```
utils.js:424 Warning: No implementation found for action type 'deleteGuarantorChannel'
utils.js:424 Warning: No implementation found for action type 'deleteTargetChannel'
utils.js:424 Warning: No implementation found for action type 'deleteJointChannel'
```

**Update**
While testing this on **master**, I noticed that the warnings that I mentioned above with virtual-funding, **also appear at the end of the leecher's download** (when closing the channel after finishing the download), so it's not related to the unexpected cancellation of the torrent.

------------------

In #1781 I added a `console.log('CANCEL BUTTON WAS CLICKED') `so that the leecher's log shows when the cancel button is pressed: The last lines of the [logs in circleCI](https://app.circleci.com/pipelines/github/statechannels/monorepo/6342/workflows/fa6b8e9c-32b6-4b41-8d12-6fbd8b2e376d/jobs/26440/steps), show the error that I was talking about.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run all the things with `DEV_SC=virtual-funding` or the direct funding equivalent.
2. Seed a file in a browser and start downloading it in another
3. After a couple of turns passed, cancel the download
4. See the error (the torrent download bar is not supposed to still be shown, the seeder shouldn't see the leecher as connected (notice the number of peers connected didn't change))

**Screenshots**
![image](https://user-images.githubusercontent.com/10502605/81771643-efb99900-94b9-11ea-8add-7bfa05021670.png) 
_screenshot of this in production, after making the screenshot, I pressed the cancel button again and it cancelled the torrent like it was supposed to_

**Comment by andrewgordstewart** [comment]
Some notes:
```
utils.js:424 Warning: No implementation found for action type 'deleteGuarantorChannel'
utils.js:424 Warning: No implementation found for action type 'deleteTargetChannel'
utils.js:424 Warning: No implementation found for action type 'deleteJointChannel'
```

These can be ignored for now. We don't yet garbage collect any channels.

```
Browser 1 logged Missing onError handler for invocation 'signFinalState', error was 'Error: Supported state not final'. Stacktrace was 'Error: Supported state not final
    at http://localhost:3055/bundle.js:264367:15
    at Generator.next (<anonymous>)
    at fulfilled (http://localhost:3055/bundle.js:264352:58)'
```

That's probably [this](https://github.com/statechannels/monorepo/issues/1789), which should be fixed by [this](https://github.com/statechannels/monorepo/pull/1808)

**Comment by spersico** [comment]
> Some notes:
> 
> ```
> utils.js:424 Warning: No implementation found for action type 'deleteGuarantorChannel'
> utils.js:424 Warning: No implementation found for action type 'deleteTargetChannel'
> utils.js:424 Warning: No implementation found for action type 'deleteJointChannel'
> ```
> 
> These can be ignored for now. We don't yet garbage collect any channels.
> 
> ```
> Browser 1 logged Missing onError handler for invocation 'signFinalState', error was 'Error: Supported state not final'. Stacktrace was 'Error: Supported state not final
>     at http://localhost:3055/bundle.js:264367:15
>     at Generator.next (<anonymous>)
>     at fulfilled (http://localhost:3055/bundle.js:264352:58)'
> ```
> 
> That's probably [this](https://github.com/statechannels/monorepo/issues/1789), which should be fixed by [this](https://github.com/statechannels/monorepo/pull/1808)

Seems like it (the error in the log it's no longer appears), but it seems like something it's still not working okay (both in master and in #1781) because cancelling it's still not working correctly in the current master and the test it's still not passing: https://app.circleci.com/pipelines/github/statechannels/monorepo/6363/workflows/d19bbd6a-db7f-4da8-b9cb-047f77ca085a/jobs/26555/steps

**Comment by andrewgordstewart** [comment]
Draft, working PR:
https://github.com/statechannels/monorepo/pull/1997

On 155aebc, when I run the stress test, I usually get `Error: Wallet Error 300: Not your turn`:

**Screenshot**
<img width="1680" alt="Screen Shot 2020-05-27 at 3 16 08 PM" src="https://user-images.githubusercontent.com/8432675/83077818-1389ec80-a02d-11ea-80c5-22311a98cda6.png">


**Logs**
[web3torrent.Wed, 27 May 2020 22_15_12 GMT.a4b574960.0x44dF019c9cc8c757C66B269820957bC2b2B13d73.pino.log](https://github.com/statechannels/monorepo/files/4692132/web3torrent.Wed.27.May.2020.22_15_12.GMT.a4b574960.0x44dF019c9cc8c757C66B269820957bC2b2B13d73.pino.log)

I will post a detailed investigation in a following comment, but I think the web3torrent code is just _incorrectly_ waiting for my turn, based on some indexing errors.

**Comment by andrewgordstewart** [comment]
```
cp ~/Downloads/web3torrent.Wed,\ 27\ May\ 2020\ 22_15_12\ GMT.a4b574960.0x44dF019c9cc8c757C66B269820957bC2b2B13d73.pino.log original.log

prettee () {  
 tee $1.log | pino-pretty > $1.pretty.log
}

# Just to be sure...

cat original.log | jq -s -c 'sort_by(.time) | .[]' | prettee sorted

ERROR_CHANNEL=0x3c92e09bf2942ffd6791d54cf121756bac3935969dea8553467bc0ecd21f24b5
grep \$ERROR_CHANNEL sorted.log | prettee withChannelId
```

Get a quick look at the messages
```
cat withChannelId.log | jq -c '{msg, time, level}' | prettee messages
```

Here's the error thrown within the transaction:
```
❯ grep '1590617696276' sorted.log | jq '{msg, time, level, updateData, existingState: { turnNum: .existingState.turnNum._hex, participants: .existingState.participants}}' | pino-pretty 

{
  "msg": "Updating channel when not my turn",
  "time": 1590617696276,
  "level": 50,
  "updateData": {
    "isFinal": true
  },
  "existingState": {
    "turnNum": "0x03",
    "participants": [
      {
        "participantId": "0xCdE014f075178dDa6BcBb2f8485dAB6D65F7bfb7",
        "signingAddress": "0xCdE014f075178dDa6BcBb2f8485dAB6D65F7bfb7",
        "destination": "0x00000000000000000000000056A32fFf5E5A8B40d6A21538579fB8922DF5258c"
      },
      {
        "participantId": "0x44dF019c9cc8c757C66B269820957bC2b2B13d73",
        "signingAddress": "0x44dF019c9cc8c757C66B269820957bC2b2B13d73",
        "destination": "0x000000000000000000000000760bf27cd45036a6C486802D30B5D90CfFBE31FE"
      }
    ]
  }
}
```

The channel ids don't match here. That points out a [bug in my changeset](https://github.com/statechannels/monorepo/blob/155aebc06153b16b806f1d1d19ed9da32658cfb7/packages/web3torrent/src/clients/payment-channel-client.ts#L224-L227). However, it's a red herring.

```
❯ grep '1590617696324' sorted.log | pino-pretty
[1590617696324] INFO  (web3torrent): It's my turn, closing the channel
    channelId: "0x3c92e09bf2942ffd6791d54cf121756bac3935969dea8553467bc0ecd21f24b5"
    cs: {
      "channelId": "0x4dee254609862893d07bdda87ff100448689486c8dfe10f0b41c2dbb11c4c2cb",
      "turnNum": {
        "_hex": "0x0000000000000000000000000000000000000000000000000000000000000017"
      },
      "status": "closing",
      "beneficiary": {
        "signingAddress": "0xAaef675c807661625F44cC9fBca65A3606Bf313A",
        "outcomeAddress": "0x000000000000000000000000d4Fa489Eacc52BA59438993f37Be9fcC20090E39",
        "balance": "0x000000000000000000000000000000000000000000000000000000000007c000"
      },
      "payer": {
        "signingAddress": "0x44dF019c9cc8c757C66B269820957bC2b2B13d73",
        "outcomeAddress": "0x000000000000000000000000760bf27cd45036a6C486802D30B5D90CfFBE31FE",
        "balance": "0x0000000000000000000000000000000000000000000000000000000000002f40"
      }
    }
    me: "0x44dF019c9cc8c757C66B269820957bC2b2B13d73"
```



The error channel is the 4th entry in the channels table.
Inspecting points out that
- the turn number in the store is indeed 0x03:
- My index in that channel is 1
- So it is _not_ my turn

```
❯ grep 1590617696371 sorted.log | jq -c "{ msg, level, time, channel: .store.channels[4] }" | pino-pretty

[1590617696371] ERROR: Transaction error
    channel: {
      "key": "0x3c92e09bf2942ffd6791d54cf121756bac3935969dea8553467bc0ecd21f24b5",
      "value": {
        "stateVariables": [
          {
            "outcome": {
              "type": "SimpleAllocation",
              "assetHolderAddress": "0xA5E1de55620abb28965d3da92Be02b757dAA524C",
              "allocationItems": [
                {
                  "destination": "0x00000000000000000000000056A32fFf5E5A8B40d6A21538579fB8922DF5258c",
                  "amount": {
                    "_hex": "0x00",
                    "_isBigNumber": true
                  }
                },
                {
                  "destination": "0x000000000000000000000000760bf27cd45036a6C486802D30B5D90CfFBE31FE",
                  "amount": {
                    "_hex": "0x07ef40",
                    "_isBigNumber": true
                  }
                }
              ]
            },
            "turnNum": {
              "_hex": "0x03",
              "_isBigNumber": true
            },
            "appData": "0x0000000000000000000000000000000000000000000000000000000000000000",
            "isFinal": false,
            "stateHash": "0x72bb83d7d240aa031bea9052d388bbb73cb4b3d786e44f093a81c15d432a0414",
            "signatures": [
              {
                "signature": "0x0649348e6b65e13eb297f569acef0f1499d0bfd06296c6dc82439697be5aad8c46023724b32f395a0bd00cc8636e2b0dc8af0ec0ae1bec6fa3c5414c6e6f6a1f1c",
                "signer": "0x44dF019c9cc8c757C66B269820957bC2b2B13d73"
              },
              {
                "signature": "0x279a575a23cb8f0616e4a2379af398b905600753d4347e0da78d5ddd889702b65396673b47fbec0bd4fb675737c856b3ca014fd029f408d7060dd6ff16f4b2461b",
                "signer": "0xCdE014f075178dDa6BcBb2f8485dAB6D65F7bfb7"
              }
            ]
          }
        ],
        "channelConstants": {
          "chainId": "9001",
          "participants": [
            {
              "participantId": "0xCdE014f075178dDa6BcBb2f8485dAB6D65F7bfb7",
              "signingAddress": "0xCdE014f075178dDa6BcBb2f8485dAB6D65F7bfb7",
              "destination": "0x00000000000000000000000056A32fFf5E5A8B40d6A21538579fB8922DF5258c"
            },
            {
              "participantId": "0x44dF019c9cc8c757C66B269820957bC2b2B13d73",
              "signingAddress": "0x44dF019c9cc8c757C66B269820957bC2b2B13d73",
              "destination": "0x000000000000000000000000760bf27cd45036a6C486802D30B5D90CfFBE31FE"
            }
          ],
          "appDefinition": "0x430869383d611bBB1ce7Ca207024E7901bC26b40",
          "challengeDuration": "300",
          "channelNonce": "0"
        },
        "funding": {
          "type": "Virtual",
          "jointChannelId": "0xeb8fcd8d70a893fdffbf70153e244addd34d68aa86f9a0f2dc6a64a56347866b"
        },
        "myIndex": 1,
        "applicationDomain": "localhost:3000"
      }
    }
```

That's because Index.Payer is 0, even though the payer is at index 1...
https://github.com/statechannels/monorepo/blob/155aebc06153b16b806f1d1d19ed9da32658cfb7/packages/web3torrent/src/clients/payment-channel-client.ts#L53-L56

**Comment by andrewgordstewart** [comment]
> That's because Index.Payer is 0, even though the payer is at index 1...
> https://github.com/statechannels/monorepo/blob/155aebc06153b16b806f1d1d19ed9da32658cfb7/packages/web3torrent/src/clients/payment-channel-client.ts#L53-L56

When I fix this, the stress test reliably fails:
```

  ● One file, three leechers, one seeder › Allows peers to share a torrent completely

    Error: Wallet Error 400: Channel not found
```

**Comment by andrewgordstewart** [comment]
> > That's because Index.Payer is 0, even though the payer is at index 1...
> > https://github.com/statechannels/monorepo/blob/155aebc06153b16b806f1d1d19ed9da32658cfb7/packages/web3torrent/src/clients/payment-channel-client.ts#L53-L56
> 
> When I fix this, the stress test reliably fails:
> 
> ```
> 
>   ● One file, three leechers, one seeder › Allows peers to share a torrent completely
> 
>     Error: Wallet Error 400: Channel not found
> ```

(Note that the error code is [incorrect](https://github.com/statechannels/monorepo/blob/155aebc06153b16b806f1d1d19ed9da32658cfb7/packages/xstate-wallet/src/workflows/application.ts#L353-L354))

**Comment by andrewgordstewart** [comment]
After some fixes ....

[web3torrent.Thu, 28 May 2020 00_54_36 GMT.7e4f63bf1.0x4007574b44c869Aaee0Df517A9ac20496BA60Dc6.pino.log](https://github.com/statechannels/monorepo/files/4692616/web3torrent.Thu.28.May.2020.00_54_36.GMT.7e4f63bf1.0x4007574b44c869Aaee0Df517A9ac20496BA60Dc6.pino.log)

```
❯ cp ~/Downloads/web3torrent.Thu,\ 28\ May\ 2020\ 00_54_36\ GMT.7e4f63bf1.0x4007574b44c869Aaee0Df517A9ac20496BA60Dc6.pino.log original.log

prettee () {  
 tee $1.log | pino-pretty > $1.pretty.log
}

# Just to be sure...

cat original.log | jq -s -c 'sort_by(.time) | .[]' | prettee sorted

ERROR_CHANNEL=0xce0ff77bb5210a4fde0e32c05f1ade1acfeb91eca269fa45c4c420c8c66410de
grep $ERROR_CHANNEL sorted.log | prettee withChannelId

# Get a quick look at the messages

cat withChannelId.log | jq -c '{msg, time, level}' | prettee messages

cat sorted.log | jq -c 'select (.time >= 1590627136136 and .time <= 1590627136293)' | prettee aroundError

head -n 2 aroundError.log | pino-pretty
```

This shows that web3torrent is still making an `UpdateChannel` RPC call:
```
[1590627136136] INFO  (web3torrent): It's my turn, closing the channel
    channelId: "0xce0ff77bb5210a4fde0e32c05f1ade1acfeb91eca269fa45c4c420c8c66410de"
    cs: {
      "channelId": "0xce0ff77bb5210a4fde0e32c05f1ade1acfeb91eca269fa45c4c420c8c66410de",
      "turnNum": {
        "_hex": "0x0000000000000000000000000000000000000000000000000000000000000004"
      },
      "status": "running",
      "beneficiary": {
        "signingAddress": "0xB6Eb0D9b1057f5055225e83f4eeBF810E78A4649",
        "outcomeAddress": "0x000000000000000000000000760bf27cd45036a6C486802D30B5D90CfFBE31FE",
        "balance": "0x0000000000000000000000000000000000000000000000000000000000000000"
      },
      "payer": {
        "signingAddress": "0x4007574b44c869Aaee0Df517A9ac20496BA60Dc6",
        "outcomeAddress": "0x00000000000000000000000056A32fFf5E5A8B40d6A21538579fB8922DF5258c",
        "balance": "0x000000000000000000000000000000000000000000000000000000000007ef40"
      }
    }
    me: "0x4007574b44c869Aaee0Df517A9ac20496BA60Dc6"
[1590627136143] INFO  (xstate-wallet): INCOMING JSONRPC REQUEST:
    jsonRpcRequest: {
      "jsonrpc": "2.0",
      "method": "UpdateChannel",
      "params": {
        "channelId": "0xce0ff77bb5210a4fde0e32c05f1ade1acfeb91eca269fa45c4c420c8c66410de",
        "participants": [
          {
            "participantId": "0xB6Eb0D9b1057f5055225e83f4eeBF810E78A4649",
            "signingAddress": "0xB6Eb0D9b1057f5055225e83f4eeBF810E78A4649",
            "destination": "0x000000000000000000000000760bf27cd45036a6C486802D30B5D90CfFBE31FE"
          },
          {
            "participantId": "0x4007574b44c869Aaee0Df517A9ac20496BA60Dc6",
            "signingAddress": "0x4007574b44c869Aaee0Df517A9ac20496BA60Dc6",
            "destination": "0x00000000000000000000000056A32fFf5E5A8B40d6A21538579fB8922DF5258c"
          }
        ],
        "allocations": [
          {
            "token": "0x0000000000000000000000000000000000000000",
            "allocationItems": [
              {
                "destination": "0x000000000000000000000000760bf27cd45036a6C486802D30B5D90CfFBE31FE",
                "amount": "0x0000000000000000000000000000000000000000000000000000000000004000"
              },
              {
                "destination": "0x00000000000000000000000056A32fFf5E5A8B40d6A21538579fB8922DF5258c",
                "amount": "0x000000000000000000000000000000000000000000000000000000000007af40"
              }
            ]
          }
        ],
        "appData": "0x0000000000000000000000000000000000000000000000000000000000000000"
      },
      "id": 62
    }
```

By the time the `CloseChannel` (dexie) transaction occurs, the channel update has already been made:
```
❯ grep 1590627136257 aroundError.log | jq -c '{msg, time, level, existingState: .existingState.turnNum._hex}' | pino-pretty
[1590627136257] ERROR: Updating channel when not my turn
    existingState: "0x05"
```
